<a href="https://colab.research.google.com/github/Leoneldshms/Trabajo-CD/blob/main/BD_cargada_sucia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Título de la Práctica: Limpieza de una Base de Datos Ensuciada
#Nombre:Nery Leonel Vega Pestaña
#Día y horario de la materia: Clase de los martes y jueves de 8:00 a 12:00

In [2]:
import pandas as pd
url="https://raw.githubusercontent.com/Leoneldshms/Trabajo-CD/refs/heads/main/df_sucio.csv"
df=pd.read_csv(url)
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.0,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.0,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205.0,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450.0,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458.0,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58877,TYLeR jOnES,54,Female,A-,Arthritis,2020-09-20,Stephanie Jones,and Kelley Sons,Medicare,1725.826151,NaN,Urgent,2020-09-30,NaN,Abnormal
58878,Ian RiCE,41,Female,A+,Obesity,2023-03-28,Charlotte Suarez,Haley-Franco,Cigna,5473.934438,141.0,Elective,2023-03-30,Aspirin,Normal
58879,jeRry Hart,18,Female,AB-,Diabetes,2019-05-24,Curtis Smith,"and Brown Ali, Barton",Cigna,21439.985430,NaN,Elective,NaN,Aspirin,Inconclusive
58880,richArd joNES,64,Male,A-,Hypertension,2022-04-17,Kenneth Brown,Mcpherson-Campos,UnitedHealthcare,18168.222093,112.0,Elective,2022-04-28,Lipitor,Inconclusive
58881,jAsoN torRES,39,Female,A-,Hypertension,2023-04-21,Mr. Stephen Garza MD,Ltd Thornton,Cigna,32162.818121,353.0,Emergency,2023-04-29,Penicillin,NaN

# Análisis Inicial de la Base de Datos

In [3]:
df.describe(include=['O'])

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Admission Type,Discharge Date,Medication,Test Results
count,56527,56527,56527,56527,56527,56527,56527,56527,56527,56527,56527,56527,56527
unique,48261,78,3,8,7,1827,39191,38092,6,3,1856,6,3
top,JeSsE WEbSter,bbb,Female,B-,Diabetes,2024-03-16,Michael Smith,bbb,Cigna,Elective,2020-03-15,Aspirin,Abnormal
freq,5,1136,27732,7097,9303,53,30,1117,11227,19058,55,11125,18948

In [4]:
df.columns

Index(['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results'],
      dtype='object')

In [5]:
df.shape

(58882, 15)

In [6]:
df.describe()

       Billing Amount   Room Number
count    55395.000000  56527.000000
mean     25553.767674    300.992163
std      14218.848049    115.282410
min      -2008.492140    101.000000
25%      13238.789016    202.000000
50%      25595.069800    302.000000
75%      37831.998403    400.000000
max      52764.276736    500.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58882 entries, 0 to 58881
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                56527 non-null  object
 1   Age                 56527 non-null  object
 2   Gender              56527 non-null  object
 3   Blood Type          56527 non-null  object
 4   Medical Condition   56527 non-null  object
 5   Date of Admission   56527 non-null  object
 6   Doctor              56527 non-null  object
 7   Hospital            56527 non-null  object
 8   Insurance Provider  56527 non-null  object
 9   Billing Amount      55395 non-null  float64
 10  Room Number         56527 non-null  float64
 11  Admission Type      56527 non-null  object
 12  Discharge Date      56527 non-null  object
 13  Medication          56527 non-null  object
 14  Test Results        56527 non-null  object
dtypes: float64(2), object(13)
memory usage: 6.7+ MB

In [8]:
df.isnull().mean()*100

Name                  3.999524
Age                   3.999524
Gender                3.999524
Blood Type            3.999524
Medical Condition     3.999524
Date of Admission     3.999524
Doctor                3.999524
Hospital              3.999524
Insurance Provider    3.999524
Billing Amount        5.922014
Room Number           3.999524
Admission Type        3.999524
Discharge Date        3.999524
Medication            3.999524
Test Results          3.999524
dtype: float64

In [9]:
df.isnull().sum()

Name                  2355
Age                   2355
Gender                2355
Blood Type            2355
Medical Condition     2355
Date of Admission     2355
Doctor                2355
Hospital              2355
Insurance Provider    2355
Billing Amount        3487
Room Number           2355
Admission Type        2355
Discharge Date        2355
Medication            2355
Test Results          2355
dtype: int64

In [10]:
df.duplicated().sum()

922

In [11]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
58877    False
58878    False
58879    False
58880     True
58881    False
Length: 58882, dtype: bool

In [12]:
colum_1=['Gender', 'Blood Type', 'Medical Condition',
       'Insurance Provider',
       'Admission Type',
       'Medication', 'Test Results']

In [13]:
for i in colum_1:
  print (f"En la columna: {i}, los valores unicos son: {df[i].unique()}")

En la columna: Gender, los valores unicos son: ['Male' 'Female' nan 'bbb']
En la columna: Blood Type, los valores unicos son: ['B-' 'A+' 'A-' 'O+' 'AB+' 'AB-' 'B+' nan 'O-']
En la columna: Medical Condition, los valores unicos son: ['Cancer' 'Obesity' 'Diabetes' 'Asthma' 'Hypertension' nan 'Arthritis'
 'bbb']
En la columna: Insurance Provider, los valores unicos son: ['Blue Cross' 'Medicare' 'Aetna' 'UnitedHealthcare' 'Cigna' nan 'bbb']
En la columna: Admission Type, los valores unicos son: ['Urgent' 'Emergency' 'Elective' nan]
En la columna: Medication, los valores unicos son: ['Paracetamol' 'Ibuprofen' 'Aspirin' 'Penicillin' 'Lipitor' nan 'bbb']
En la columna: Test Results, los valores unicos son: ['Normal' 'Inconclusive' 'Abnormal' nan]

In [14]:
for i in colum_1:
  print (f" -En la columna: {i}, los valores unicos son: {df[i].value_counts()}")

 -En la columna: Gender, los valores unicos son: Gender
Female    27732
Male      27666
bbb        1129
Name: count, dtype: int64
 -En la columna: Blood Type, los valores unicos son: Blood Type
B-     7097
A-     7096
AB+    7076
AB-    7072
A+     7070
B+     7067
O+     7047
O-     7002
Name: count, dtype: int64
 -En la columna: Medical Condition, los valores unicos son: Medical Condition
Diabetes        9303
Arthritis       9300
Hypertension    9228
Obesity         9206
Cancer          9192
Asthma          9165
bbb             1133
Name: count, dtype: int64
 -En la columna: Insurance Provider, los valores unicos son: Insurance Provider
Cigna               11227
Medicare            11106
UnitedHealthcare    11080
Blue Cross          11032
Aetna               10954
bbb                  1128
Name: count, dtype: int64
 -En la columna: Admission Type, los valores unicos son: Admission Type
Elective     19058
Urgent       18922
Emergency    18547
Name: count, dtype: int64
 -En la columna: Medication, los valores unicos son: Medication
Aspirin        11125
Lipitor        11114
Ibuprofen      11109
Penicillin     11062
Paracetamol    10975
bbb             1142
Name: count, dtype: int64
 -En la columna: Test Results, los valores unicos son: Test Results
Abnormal        18948
Normal          18843
Inconclusive    18736
Name: count, dtype: int64

In [15]:
colum_2=['Name', 'Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission', 'Doctor', 'Hospital', 'Insurance Provider',
       'Billing Amount', 'Room Number', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results']

In [16]:
for i in colum_2:
  print (f"En la columna: {i}, los valores unicos son: {df[i].nunique()}")

En la columna: Name, los valores unicos son: 48261
En la columna: Age, los valores unicos son: 78
En la columna: Gender, los valores unicos son: 3
En la columna: Blood Type, los valores unicos son: 8
En la columna: Medical Condition, los valores unicos son: 7
En la columna: Date of Admission, los valores unicos son: 1827
En la columna: Doctor, los valores unicos son: 39191
En la columna: Hospital, los valores unicos son: 38092
En la columna: Insurance Provider, los valores unicos son: 6
En la columna: Billing Amount, los valores unicos son: 47487
En la columna: Room Number, los valores unicos son: 400
En la columna: Admission Type, los valores unicos son: 3
En la columna: Discharge Date, los valores unicos son: 1856
En la columna: Medication, los valores unicos son: 6
En la columna: Test Results, los valores unicos son: 3

In [17]:
df['Age'].value_counts()

Age
bbb    1136
38      899
37      886
57      878
34      869
       ...
16       24
88       23
14       16
13       15
89        8
Name: count, Length: 78, dtype: int64

In [18]:
df['Name'].value_counts()

Name
JeSsE WEbSter     5
DEBBiE COX        5
pAul WarnEr       4
DeANNA PoWeLl     4
TYLER GREgorY     4
                 ..
JenNiFER SCOtT    1
RoBeRT PIerCE     1
CoDy rOBeRTs      1
JAmES TuRNer      1
AMANdA waRd       1
Name: count, Length: 48261, dtype: int64

In [19]:
df['Doctor'].value_counts()

Doctor
Michael Smith        30
Robert Smith         23
John Smith           23
James Smith          20
Michael Johnson      20
                     ..
Kathryn Martinez      1
Victoria Campbell     1
Jeffrey Shea          1
Carolyn Herman        1
Lauren Guerrero       1
Name: count, Length: 39191, dtype: int64

In [20]:
df['Hospital'].value_counts()

Hospital
bbb                             1117
LLC Smith                         43
Ltd Smith                         40
Smith Ltd                         38
Johnson PLC                       38
                                ...
Woods-Walter                       1
Combs Ltd                          1
Mason Christian Stewart, and       1
Mcgrath-Lopez                      1
Harris Watts, Taylor and           1
Name: count, Length: 38092, dtype: int64

In [21]:
df['Date of Admission'].value_counts()

Date of Admission
2024-03-16    53
2022-01-09    53
2022-11-15    50
2023-08-10    50
2021-01-03    49
              ..
2022-02-05    14
2023-07-28    14
2023-05-11    14
2022-05-28    13
2019-07-22    12
Name: count, Length: 1827, dtype: int64

# Eliminacion o impiutacion de valores faltates

In [22]:
df1=df

In [23]:
df1

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.0,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.0,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205.0,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450.0,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458.0,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58877,TYLeR jOnES,54,Female,A-,Arthritis,2020-09-20,Stephanie Jones,and Kelley Sons,Medicare,1725.826151,NaN,Urgent,2020-09-30,NaN,Abnormal
58878,Ian RiCE,41,Female,A+,Obesity,2023-03-28,Charlotte Suarez,Haley-Franco,Cigna,5473.934438,141.0,Elective,2023-03-30,Aspirin,Normal
58879,jeRry Hart,18,Female,AB-,Diabetes,2019-05-24,Curtis Smith,"and Brown Ali, Barton",Cigna,21439.985430,NaN,Elective,NaN,Aspirin,Inconclusive
58880,richArd joNES,64,Male,A-,Hypertension,2022-04-17,Kenneth Brown,Mcpherson-Campos,UnitedHealthcare,18168.222093,112.0,Elective,2022-04-28,Lipitor,Inconclusive
58881,jAsoN torRES,39,Female,A-,Hypertension,2023-04-21,Mr. Stephen Garza MD,Ltd Thornton,Cigna,32162.818121,353.0,Emergency,2023-04-29,Penicillin,NaN

In [24]:
df1['Name'].fillna('No tiene', inplace=True)
df1['Name'].isnull().sum()

<ipython-input-24-e6d4c3166eb6>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Name'].fillna('No tiene', inplace=True)

0

In [25]:
df1['Name'].value_counts()

Name
No tiene           2355
DEBBiE COX            5
JeSsE WEbSter         5
deboRAh SINGH         4
barBAra paRSonS       4
                   ...
JenNiFER SCOtT        1
RoBeRT PIerCE         1
CoDy rOBeRTs          1
JAmES TuRNer          1
AMANdA waRd           1
Name: count, Length: 48262, dtype: int64

In [26]:
df1['Age'].fillna('Sin edad', inplace=True)
df1['Age'] = pd.to_numeric(df1['Age'], errors='coerce')
df1['Age'].fillna(df1['Age'].mean(), inplace=True)
df1['Age'].isnull().sum()

<ipython-input-26-2ceeb4f91dfa>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Age'].fillna('Sin edad', inplace=True)
<ipython-input-26-2ceeb4f91dfa>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Age'].fillna(df1['Age'].mean(), inplace=True)

0

In [27]:
df1['Age'].value_counts()

Age
51.520265    3491
38.000000     899
37.000000     886
57.000000     878
34.000000     869
             ...
16.000000      24
88.000000      23
14.000000      16
13.000000      15
89.000000       8
Name: count, Length: 78, dtype: int64

In [28]:
df1['Gender'].fillna('Otro', inplace=True)
df1['Gender'].isnull().sum()

<ipython-input-28-73c2da339adf>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Gender'].fillna('Otro', inplace=True)

0

In [29]:
df1['Blood Type'].fillna('No tiene', inplace=True)
df1['Blood Type'].isnull().sum()

<ipython-input-29-22433333e185>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Blood Type'].fillna('No tiene', inplace=True)

0

In [30]:
df1['Medical Condition'].fillna('No especificada', inplace=True)
df1['Medical Condition'].isnull().sum()

<ipython-input-30-465574d65b9f>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Medical Condition'].fillna('No especificada', inplace=True)

0

In [31]:
df1=df1.dropna(subset=['Date of Admission'])
df1['Date of Admission'].isnull().sum()

0

In [32]:
df1['Doctor'].fillna('No tiene', inplace=True)
df1['Doctor'].isnull().sum()

<ipython-input-32-f958d341e1df>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Doctor'].fillna('No tiene', inplace=True)
<ipython-input-32-f958d341e1df>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Doctor'].fillna('No tiene', inplace=True)

0

In [33]:
df1['Hospital'].fillna('No tiene', inplace=True)
df1['Hospital'].isnull().sum()

<ipython-input-33-0c72a6bb3328>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Hospital'].fillna('No tiene', inplace=True)
<ipython-input-33-0c72a6bb3328>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Hospital'].fillna('No tiene', inplace=True)

0

In [34]:
df1['Insurance Provider'].fillna('No tiene', inplace=True)
df1['Insurance Provider'].isnull().sum()

<ipython-input-34-45954d74c02a>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Insurance Provider'].fillna('No tiene', inplace=True)
<ipython-input-34-45954d74c02a>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Insurance Provider'].fillna('No tiene', inplace=True)

0

In [35]:
df1['Billing Amount'] = pd.to_numeric(df1['Billing Amount'], errors='coerce')
df1['Billing Amount'].fillna(df1['Billing Amount'].mean(), inplace=True)
df1['Billing Amount'].isnull().sum()

<ipython-input-35-fb46c20a3380>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Billing Amount'] = pd.to_numeric(df1['Billing Amount'], errors='coerce')
<ipython-input-35-fb46c20a3380>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Billing Amount'].fillna(df1['Billing Amount'].mean(), inplace=True)
<ipython-input-35-fb46c20a3380>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Billing Amount'].fillna(df1['Billing Amount'].mean(), inplace=True)

0

In [36]:
df1['Room Number'] = pd.to_numeric(df1['Room Number'], errors='coerce')
df1['Room Number'].fillna(df1['Room Number'].mean(), inplace=True)
df1['Room Number'].isnull().sum()

<ipython-input-36-59e402d62fdb>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Room Number'] = pd.to_numeric(df1['Room Number'], errors='coerce')
<ipython-input-36-59e402d62fdb>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Room Number'].fillna(df1['Room Number'].mean(), inplace=True)
<ipython-input-36-59e402d62fdb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Room Number'].fillna(df1['Room Number'].mean(), inplace=True)

0

In [37]:
df1['Admission Type'].fillna('Otro', inplace=True)
df1['Admission Type'].isnull().sum()

<ipython-input-37-8f6c8697d114>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Admission Type'].fillna('Otro', inplace=True)
<ipython-input-37-8f6c8697d114>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Admission Type'].fillna('Otro', inplace=True)

0

In [38]:
df1=df1.dropna(subset=['Discharge Date'])
df1['Discharge Date'].isnull().sum()

0

In [39]:
df1['Medication'].fillna('No especificado', inplace=True)
df1['Medication'].isnull().sum()

<ipython-input-39-662ad1b18432>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Medication'].fillna('No especificado', inplace=True)
<ipython-input-39-662ad1b18432>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Medication'].fillna('No especificado', inplace=True)

0

In [40]:
df1['Test Results'].fillna('En progreso', inplace=True)
df1['Test Results'].isnull().sum()

<ipython-input-40-0b4ed3b3e3d7>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df1['Test Results'].fillna('En progreso', inplace=True)

0

In [41]:
df1

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30.0,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.000000,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62.0,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.000000,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76.0,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205.000000,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28.0,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450.000000,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43.0,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458.000000,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58876,madiSoN THomAS,71.0,Female,AB+,Obesity,2019-05-24,Mrs. Christina Willis MD,"Logan Caldwell, and Chavez",Aetna,-557.014700,173.000000,Urgent,2019-06-20,Paracetamol,Abnormal
58877,TYLeR jOnES,54.0,Female,A-,Arthritis,2020-09-20,Stephanie Jones,and Kelley Sons,Medicare,1725.826151,301.024893,Urgent,2020-09-30,No especificado,Abnormal
58878,Ian RiCE,41.0,Female,A+,Obesity,2023-03-28,Charlotte Suarez,Haley-Franco,Cigna,5473.934438,141.000000,Elective,2023-03-30,Aspirin,Normal
58880,richArd joNES,64.0,Male,A-,Hypertension,2022-04-17,Kenneth Brown,Mcpherson-Campos,UnitedHealthcare,18168.222093,112.000000,Elective,2022-04-28,Lipitor,Inconclusive
58881,jAsoN torRES,39.0,Female,A-,Hypertension,2023-04-21,Mr. Stephen Garza MD,Ltd Thornton,Cigna,32162.818121,353.000000,Emergency,2023-04-29,Penicillin,En progreso

In [42]:
df1.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

# eliminar duplicados

In [43]:
df1.duplicated().sum()

925

In [44]:
df1.drop_duplicates(inplace=True)

In [45]:
df1.duplicated().sum()

0

In [46]:
df1

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30.0,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.000000,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62.0,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.000000,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76.0,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205.000000,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28.0,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450.000000,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43.0,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458.000000,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58873,AngELA AdAmS,70.0,Female,AB+,Obesity,2020-09-06,Thomas Jackson,Lowe Group,Aetna,27378.719844,351.000000,Emergency,2020-09-10,Ibuprofen,Inconclusive
58875,TAMmIE yOUng,19.0,Male,No tiene,Cancer,2019-06-07,James Kelly,Williams Inc,Medicare,43520.710165,403.000000,Elective,2019-06-13,No especificado,Normal
58877,TYLeR jOnES,54.0,Female,A-,Arthritis,2020-09-20,Stephanie Jones,and Kelley Sons,Medicare,1725.826151,301.024893,Urgent,2020-09-30,No especificado,Abnormal
58878,Ian RiCE,41.0,Female,A+,Obesity,2023-03-28,Charlotte Suarez,Haley-Franco,Cigna,5473.934438,141.000000,Elective,2023-03-30,Aspirin,Normal
58881,jAsoN torRES,39.0,Female,A-,Hypertension,2023-04-21,Mr. Stephen Garza MD,Ltd Thornton,Cigna,32162.818121,353.000000,Emergency,2023-04-29,Penicillin,En progreso

# correccion de valores invalid

In [47]:
lista=df.columns

In [48]:
for i in lista:
    print(f"En la columna {i} los valores invalid son: {df1[df1[i] == 'bbb'].shape[0]}")

En la columna Name los valores invalid son: 0
En la columna Age los valores invalid son: 0
En la columna Gender los valores invalid son: 1049
En la columna Blood Type los valores invalid son: 0
En la columna Medical Condition los valores invalid son: 1031
En la columna Date of Admission los valores invalid son: 0
En la columna Doctor los valores invalid son: 0
En la columna Hospital los valores invalid son: 1002
En la columna Insurance Provider los valores invalid son: 1038
En la columna Billing Amount los valores invalid son: 0
En la columna Room Number los valores invalid son: 0
En la columna Admission Type los valores invalid son: 0
En la columna Discharge Date los valores invalid son: 0
En la columna Medication los valores invalid son: 1062
En la columna Test Results los valores invalid son: 0

In [49]:
df2=df1
for i in lista:
    df2=df2[df2[i] != 'bbb']
df2

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30.0,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.000000,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62.0,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.000000,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76.0,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205.000000,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28.0,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450.000000,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43.0,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458.000000,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58873,AngELA AdAmS,70.0,Female,AB+,Obesity,2020-09-06,Thomas Jackson,Lowe Group,Aetna,27378.719844,351.000000,Emergency,2020-09-10,Ibuprofen,Inconclusive
58875,TAMmIE yOUng,19.0,Male,No tiene,Cancer,2019-06-07,James Kelly,Williams Inc,Medicare,43520.710165,403.000000,Elective,2019-06-13,No especificado,Normal
58877,TYLeR jOnES,54.0,Female,A-,Arthritis,2020-09-20,Stephanie Jones,and Kelley Sons,Medicare,1725.826151,301.024893,Urgent,2020-09-30,No especificado,Abnormal
58878,Ian RiCE,41.0,Female,A+,Obesity,2023-03-28,Charlotte Suarez,Haley-Franco,Cigna,5473.934438,141.000000,Elective,2023-03-30,Aspirin,Normal
58881,jAsoN torRES,39.0,Female,A-,Hypertension,2023-04-21,Mr. Stephen Garza MD,Ltd Thornton,Cigna,32162.818121,353.000000,Emergency,2023-04-29,Penicillin,En progreso

In [50]:
for i in lista:
    print(f"En la columna {i} los valores invalid son: {df2[df2[i] == 'bbb'].shape[0]}")
df2

En la columna Name los valores invalid son: 0
En la columna Age los valores invalid son: 0
En la columna Gender los valores invalid son: 0
En la columna Blood Type los valores invalid son: 0
En la columna Medical Condition los valores invalid son: 0
En la columna Date of Admission los valores invalid son: 0
En la columna Doctor los valores invalid son: 0
En la columna Hospital los valores invalid son: 0
En la columna Insurance Provider los valores invalid son: 0
En la columna Billing Amount los valores invalid son: 0
En la columna Room Number los valores invalid son: 0
En la columna Admission Type los valores invalid son: 0
En la columna Discharge Date los valores invalid son: 0
En la columna Medication los valores invalid son: 0
En la columna Test Results los valores invalid son: 0

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30.0,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.000000,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62.0,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.000000,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76.0,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205.000000,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28.0,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450.000000,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43.0,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458.000000,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58873,AngELA AdAmS,70.0,Female,AB+,Obesity,2020-09-06,Thomas Jackson,Lowe Group,Aetna,27378.719844,351.000000,Emergency,2020-09-10,Ibuprofen,Inconclusive
58875,TAMmIE yOUng,19.0,Male,No tiene,Cancer,2019-06-07,James Kelly,Williams Inc,Medicare,43520.710165,403.000000,Elective,2019-06-13,No especificado,Normal
58877,TYLeR jOnES,54.0,Female,A-,Arthritis,2020-09-20,Stephanie Jones,and Kelley Sons,Medicare,1725.826151,301.024893,Urgent,2020-09-30,No especificado,Abnormal
58878,Ian RiCE,41.0,Female,A+,Obesity,2023-03-28,Charlotte Suarez,Haley-Franco,Cigna,5473.934438,141.000000,Elective,2023-03-30,Aspirin,Normal
58881,jAsoN torRES,39.0,Female,A-,Hypertension,2023-04-21,Mr. Stephen Garza MD,Ltd Thornton,Cigna,32162.818121,353.000000,Emergency,2023-04-29,Penicillin,En progreso

#Correccion de tipos de datos

In [51]:
df2=df2.drop(columns=['Name', 'Doctor','Room Number'])
df2

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Hospital,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results
0,30.0,Male,B-,Cancer,2024-01-31,Sons and Miller,Blue Cross,18856.281306,Urgent,2024-02-02,Paracetamol,Normal
1,62.0,Male,A+,Obesity,2019-08-20,Kim Inc,Medicare,33643.327287,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,76.0,Female,A-,Obesity,2022-09-22,Cook PLC,Aetna,27955.096079,Emergency,2022-10-07,Aspirin,Normal
3,28.0,Female,O+,Diabetes,2020-11-18,"Hernandez Rogers and Vang,",Medicare,37909.782410,Elective,2020-12-18,Ibuprofen,Abnormal
4,43.0,Female,AB+,Cancer,2022-09-19,White-White,Aetna,14238.317814,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...
58873,70.0,Female,AB+,Obesity,2020-09-06,Lowe Group,Aetna,27378.719844,Emergency,2020-09-10,Ibuprofen,Inconclusive
58875,19.0,Male,No tiene,Cancer,2019-06-07,Williams Inc,Medicare,43520.710165,Elective,2019-06-13,No especificado,Normal
58877,54.0,Female,A-,Arthritis,2020-09-20,and Kelley Sons,Medicare,1725.826151,Urgent,2020-09-30,No especificado,Abnormal
58878,41.0,Female,A+,Obesity,2023-03-28,Haley-Franco,Cigna,5473.934438,Elective,2023-03-30,Aspirin,Normal
58881,39.0,Female,A-,Hypertension,2023-04-21,Ltd Thornton,Cigna,32162.818121,Emergency,2023-04-29,Penicillin,En progreso

In [52]:
df2.columns

Index(['Age', 'Gender', 'Blood Type', 'Medical Condition', 'Date of Admission',
       'Hospital', 'Insurance Provider', 'Billing Amount', 'Admission Type',
       'Discharge Date', 'Medication', 'Test Results'],
      dtype='object')

In [53]:
list1=df2.columns
df3=df2

In [54]:
for i in list1:
    print(f"En la columna {i} los valores sin datos de enfermedad son: {df3[df3[i] == 'No especificada'].shape[0]}")

En la columna Age los valores sin datos de enfermedad son: 0
En la columna Gender los valores sin datos de enfermedad son: 0
En la columna Blood Type los valores sin datos de enfermedad son: 0
En la columna Medical Condition los valores sin datos de enfermedad son: 1999
En la columna Date of Admission los valores sin datos de enfermedad son: 0
En la columna Hospital los valores sin datos de enfermedad son: 0
En la columna Insurance Provider los valores sin datos de enfermedad son: 0
En la columna Billing Amount los valores sin datos de enfermedad son: 0
En la columna Admission Type los valores sin datos de enfermedad son: 0
En la columna Discharge Date los valores sin datos de enfermedad son: 0
En la columna Medication los valores sin datos de enfermedad son: 0
En la columna Test Results los valores sin datos de enfermedad son: 0

In [55]:

for i in list1:
    df3=df3[df3[i] != 'No especificada']
df3

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Hospital,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results
0,30.0,Male,B-,Cancer,2024-01-31,Sons and Miller,Blue Cross,18856.281306,Urgent,2024-02-02,Paracetamol,Normal
1,62.0,Male,A+,Obesity,2019-08-20,Kim Inc,Medicare,33643.327287,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,76.0,Female,A-,Obesity,2022-09-22,Cook PLC,Aetna,27955.096079,Emergency,2022-10-07,Aspirin,Normal
3,28.0,Female,O+,Diabetes,2020-11-18,"Hernandez Rogers and Vang,",Medicare,37909.782410,Elective,2020-12-18,Ibuprofen,Abnormal
4,43.0,Female,AB+,Cancer,2022-09-19,White-White,Aetna,14238.317814,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...
58873,70.0,Female,AB+,Obesity,2020-09-06,Lowe Group,Aetna,27378.719844,Emergency,2020-09-10,Ibuprofen,Inconclusive
58875,19.0,Male,No tiene,Cancer,2019-06-07,Williams Inc,Medicare,43520.710165,Elective,2019-06-13,No especificado,Normal
58877,54.0,Female,A-,Arthritis,2020-09-20,and Kelley Sons,Medicare,1725.826151,Urgent,2020-09-30,No especificado,Abnormal
58878,41.0,Female,A+,Obesity,2023-03-28,Haley-Franco,Cigna,5473.934438,Elective,2023-03-30,Aspirin,Normal
58881,39.0,Female,A-,Hypertension,2023-04-21,Ltd Thornton,Cigna,32162.818121,Emergency,2023-04-29,Penicillin,En progreso

In [56]:
df3['Billing Amount']=df3['Billing Amount'].astype(float)

In [57]:
int_col=[['Age']]

for i in int_col:
    df3[i]=df3[i].astype(float)
    df3[i]=df3[i].astype(int)

In [58]:
int_col=[['Gender', 'Blood Type', 'Medical Condition',
      'Hospital', 'Insurance Provider',
      'Admission Type',
       'Medication', 'Test Results']]

for i in int_col:
    df3[i]=df3[i].astype(str)

In [59]:
df3['Date of Admission']=pd.to_datetime(df3['Date of Admission'])
df3['Discharge Date']=pd.to_datetime(df3['Discharge Date'])

In [60]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46336 entries, 0 to 58881
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 46336 non-null  int64
 1   Gender              46336 non-null  object
 2   Blood Type          46336 non-null  object
 3   Medical Condition   46336 non-null  object
 4   Date of Admission   46336 non-null  datetime64[ns]
 5   Hospital            46336 non-null  object
 6   Insurance Provider  46336 non-null  object
 7   Billing Amount      46336 non-null  float64
 8   Admission Type      46336 non-null  object
 9   Discharge Date      46336 non-null  datetime64[ns]
 10  Medication          46336 non-null  object
 11  Test Results        46336 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(1), object(8)
memory usage: 5.6+ MB

# comprobacion de que la base de datos esta limpia

In [61]:
df3

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Hospital,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results
0,30,Male,B-,Cancer,2024-01-31,Sons and Miller,Blue Cross,18856.281306,Urgent,2024-02-02,Paracetamol,Normal
1,62,Male,A+,Obesity,2019-08-20,Kim Inc,Medicare,33643.327287,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,76,Female,A-,Obesity,2022-09-22,Cook PLC,Aetna,27955.096079,Emergency,2022-10-07,Aspirin,Normal
3,28,Female,O+,Diabetes,2020-11-18,"Hernandez Rogers and Vang,",Medicare,37909.782410,Elective,2020-12-18,Ibuprofen,Abnormal
4,43,Female,AB+,Cancer,2022-09-19,White-White,Aetna,14238.317814,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...
58873,70,Female,AB+,Obesity,2020-09-06,Lowe Group,Aetna,27378.719844,Emergency,2020-09-10,Ibuprofen,Inconclusive
58875,19,Male,No tiene,Cancer,2019-06-07,Williams Inc,Medicare,43520.710165,Elective,2019-06-13,No especificado,Normal
58877,54,Female,A-,Arthritis,2020-09-20,and Kelley Sons,Medicare,1725.826151,Urgent,2020-09-30,No especificado,Abnormal
58878,41,Female,A+,Obesity,2023-03-28,Haley-Franco,Cigna,5473.934438,Elective,2023-03-30,Aspirin,Normal
58881,39,Female,A-,Hypertension,2023-04-21,Ltd Thornton,Cigna,32162.818121,Emergency,2023-04-29,Penicillin,En progreso

In [62]:
df3.describe()

,Age,Date of Admission,Billing Amount,Discharge Date
count,46336.000000,46336,46336.000000,46336
mean,51.521517,2021-10-30 22:21:45.870166016,25580.779371,2021-11-15 10:34:02.403314944
min,13.000000,2019-05-08 00:00:00,-2008.492140,2019-05-09 00:00:00
25%,36.000000,2020-07-25 00:00:00,14063.193473,2020-08-09 00:00:00
50%,51.000000,2021-10-31 00:00:00,25578.520379,2021-11-16 00:00:00
75%,67.000000,2023-02-02 00:00:00,37031.717886,2023-02-17 00:00:00
max,89.000000,2024-05-07 00:00:00,52764.276736,2024-06-04 00:00:00
std,19.008283,NaN,13781.118746,NaN

In [63]:
df3.describe(include=['O'])

,Gender,Blood Type,Medical Condition,Hospital,Insurance Provider,Admission Type,Medication,Test Results
count,46336,46336,46336,46336,46336,46336,46336,46336
unique,3,9,6,32552,6,4,6,4
top,Female,A+,Arthritis,No tiene,Cigna,Elective,Penicillin,Abnormal
freq,22324,5592,7835,1904,9052,15058,8946,14929

In [85]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 46075 entries, 0 to 58881
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Age                 46075 non-null  int64
 1   Gender              46075 non-null  object
 2   Blood Type          46075 non-null  object
 3   Medical Condition   46075 non-null  object
 4   Date of Admission   46075 non-null  datetime64[ns]
 5   Hospital            46075 non-null  object
 6   Insurance Provider  46075 non-null  object
 7   Billing Amount      46075 non-null  float64
 8   Admission Type      46075 non-null  object
 9   Discharge Date      46075 non-null  datetime64[ns]
 10  Medication          46075 non-null  object
 11  Test Results        46075 non-null  object
dtypes: datetime64[ns](2), float64(1), int64(1), object(8)
memory usage: 4.6+ MB

In [65]:
df3.isnull().mean()

Age                   0.0
Gender                0.0
Blood Type            0.0
Medical Condition     0.0
Date of Admission     0.0
Hospital              0.0
Insurance Provider    0.0
Billing Amount        0.0
Admission Type        0.0
Discharge Date        0.0
Medication            0.0
Test Results          0.0
dtype: float64

In [66]:
df3.isnull().sum()

Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Hospital              0
Insurance Provider    0
Billing Amount        0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [67]:
df3.duplicated().sum()

261

In [68]:
df3.drop_duplicates(inplace=True)

In [69]:
df3.duplicated().sum()

0

In [70]:
lista1=df3.columns

In [71]:
for i in lista1:
    print(f"En la columna {i} los valores invalid son: {df3[df3[i] == 'bbb'].shape[0]}")
df3

En la columna Age los valores invalid son: 0
En la columna Gender los valores invalid son: 0
En la columna Blood Type los valores invalid son: 0
En la columna Medical Condition los valores invalid son: 0
En la columna Date of Admission los valores invalid son: 0
En la columna Hospital los valores invalid son: 0
En la columna Insurance Provider los valores invalid son: 0
En la columna Billing Amount los valores invalid son: 0
En la columna Admission Type los valores invalid son: 0
En la columna Discharge Date los valores invalid son: 0
En la columna Medication los valores invalid son: 0
En la columna Test Results los valores invalid son: 0

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Hospital,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results
0,30,Male,B-,Cancer,2024-01-31,Sons and Miller,Blue Cross,18856.281306,Urgent,2024-02-02,Paracetamol,Normal
1,62,Male,A+,Obesity,2019-08-20,Kim Inc,Medicare,33643.327287,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,76,Female,A-,Obesity,2022-09-22,Cook PLC,Aetna,27955.096079,Emergency,2022-10-07,Aspirin,Normal
3,28,Female,O+,Diabetes,2020-11-18,"Hernandez Rogers and Vang,",Medicare,37909.782410,Elective,2020-12-18,Ibuprofen,Abnormal
4,43,Female,AB+,Cancer,2022-09-19,White-White,Aetna,14238.317814,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...
58871,70,Male,A-,Hypertension,2020-01-09,"Little, and Flores Simmons",Medicare,35445.244793,Elective,2020-01-12,Aspirin,Inconclusive
58873,70,Female,AB+,Obesity,2020-09-06,Lowe Group,Aetna,27378.719844,Emergency,2020-09-10,Ibuprofen,Inconclusive
58875,19,Male,No tiene,Cancer,2019-06-07,Williams Inc,Medicare,43520.710165,Elective,2019-06-13,No especificado,Normal
58877,54,Female,A-,Arthritis,2020-09-20,and Kelley Sons,Medicare,1725.826151,Urgent,2020-09-30,No especificado,Abnormal
58881,39,Female,A-,Hypertension,2023-04-21,Ltd Thornton,Cigna,32162.818121,Emergency,2023-04-29,Penicillin,En progreso

In [72]:
df3

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Hospital,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results
0,30,Male,B-,Cancer,2024-01-31,Sons and Miller,Blue Cross,18856.281306,Urgent,2024-02-02,Paracetamol,Normal
1,62,Male,A+,Obesity,2019-08-20,Kim Inc,Medicare,33643.327287,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,76,Female,A-,Obesity,2022-09-22,Cook PLC,Aetna,27955.096079,Emergency,2022-10-07,Aspirin,Normal
3,28,Female,O+,Diabetes,2020-11-18,"Hernandez Rogers and Vang,",Medicare,37909.782410,Elective,2020-12-18,Ibuprofen,Abnormal
4,43,Female,AB+,Cancer,2022-09-19,White-White,Aetna,14238.317814,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...
58871,70,Male,A-,Hypertension,2020-01-09,"Little, and Flores Simmons",Medicare,35445.244793,Elective,2020-01-12,Aspirin,Inconclusive
58873,70,Female,AB+,Obesity,2020-09-06,Lowe Group,Aetna,27378.719844,Emergency,2020-09-10,Ibuprofen,Inconclusive
58875,19,Male,No tiene,Cancer,2019-06-07,Williams Inc,Medicare,43520.710165,Elective,2019-06-13,No especificado,Normal
58877,54,Female,A-,Arthritis,2020-09-20,and Kelley Sons,Medicare,1725.826151,Urgent,2020-09-30,No especificado,Abnormal
58881,39,Female,A-,Hypertension,2023-04-21,Ltd Thornton,Cigna,32162.818121,Emergency,2023-04-29,Penicillin,En progreso

In [73]:
for i in lista1:
    print(f"En la columna {i} los valores sin datos son: {df3[df3[i] == 'No tiene'].shape[0]}")

En la columna Age los valores sin datos son: 0
En la columna Gender los valores sin datos son: 0
En la columna Blood Type los valores sin datos son: 1906
En la columna Medical Condition los valores sin datos son: 0
En la columna Date of Admission los valores sin datos son: 0
En la columna Hospital los valores sin datos son: 1904
En la columna Insurance Provider los valores sin datos son: 1915
En la columna Billing Amount los valores sin datos son: 0
En la columna Admission Type los valores sin datos son: 0
En la columna Discharge Date los valores sin datos son: 0
En la columna Medication los valores sin datos son: 0
En la columna Test Results los valores sin datos son: 0

In [74]:
for i in lista1:
    print(f"En la columna {i} los valores sin datos son: {df3[df3[i] == 'Otro'].shape[0]}")

En la columna Age los valores sin datos son: 0
En la columna Gender los valores sin datos son: 1935
En la columna Blood Type los valores sin datos son: 0
En la columna Medical Condition los valores sin datos son: 0
En la columna Date of Admission los valores sin datos son: 0
En la columna Hospital los valores sin datos son: 0
En la columna Insurance Provider los valores sin datos son: 0
En la columna Billing Amount los valores sin datos son: 0
En la columna Admission Type los valores sin datos son: 1880
En la columna Discharge Date los valores sin datos son: 0
En la columna Medication los valores sin datos son: 0
En la columna Test Results los valores sin datos son: 0

In [75]:
for i in lista1:
    print(f"En la columna {i} los valores sin datos de enfermedad son: {df3[df3[i] == 'No especificada'].shape[0]}")

En la columna Age los valores sin datos de enfermedad son: 0
En la columna Gender los valores sin datos de enfermedad son: 0
En la columna Blood Type los valores sin datos de enfermedad son: 0
En la columna Medical Condition los valores sin datos de enfermedad son: 0
En la columna Date of Admission los valores sin datos de enfermedad son: 0
En la columna Hospital los valores sin datos de enfermedad son: 0
En la columna Insurance Provider los valores sin datos de enfermedad son: 0
En la columna Billing Amount los valores sin datos de enfermedad son: 0
En la columna Admission Type los valores sin datos de enfermedad son: 0
En la columna Discharge Date los valores sin datos de enfermedad son: 0
En la columna Medication los valores sin datos de enfermedad son: 0
En la columna Test Results los valores sin datos de enfermedad son: 0

In [76]:
for i in lista1:
    print(f"En la columna {i} los valores sin datos de medicacion son: {df3[df3[i] == 'No especificado'].shape[0]}")

En la columna Age los valores sin datos de medicacion son: 0
En la columna Gender los valores sin datos de medicacion son: 0
En la columna Blood Type los valores sin datos de medicacion son: 0
En la columna Medical Condition los valores sin datos de medicacion son: 0
En la columna Date of Admission los valores sin datos de medicacion son: 0
En la columna Hospital los valores sin datos de medicacion son: 0
En la columna Insurance Provider los valores sin datos de medicacion son: 0
En la columna Billing Amount los valores sin datos de medicacion son: 0
En la columna Admission Type los valores sin datos de medicacion son: 0
En la columna Discharge Date los valores sin datos de medicacion son: 0
En la columna Medication los valores sin datos de medicacion son: 1921
En la columna Test Results los valores sin datos de medicacion son: 0

In [77]:
for i in lista1:
    print(f"En la columna {i} los valores sin datos de resultado son: {df3[df3[i] == 'En progreso'].shape[0]}")

En la columna Age los valores sin datos de resultado son: 0
En la columna Gender los valores sin datos de resultado son: 0
En la columna Blood Type los valores sin datos de resultado son: 0
En la columna Medical Condition los valores sin datos de resultado son: 0
En la columna Date of Admission los valores sin datos de resultado son: 0
En la columna Hospital los valores sin datos de resultado son: 0
En la columna Insurance Provider los valores sin datos de resultado son: 0
En la columna Billing Amount los valores sin datos de resultado son: 0
En la columna Admission Type los valores sin datos de resultado son: 0
En la columna Discharge Date los valores sin datos de resultado son: 0
En la columna Medication los valores sin datos de resultado son: 0
En la columna Test Results los valores sin datos de resultado son: 1879

In [78]:
for i in colum_1:
  print (f"En la columna: {i}, los valores unicos son: {df3[i].unique()}")

En la columna: Gender, los valores unicos son: ['Male' 'Female' 'Otro']
En la columna: Blood Type, los valores unicos son: ['B-' 'A+' 'A-' 'O+' 'AB+' 'AB-' 'B+' 'No tiene' 'O-']
En la columna: Medical Condition, los valores unicos son: ['Cancer' 'Obesity' 'Diabetes' 'Asthma' 'Hypertension' 'Arthritis']
En la columna: Insurance Provider, los valores unicos son: ['Blue Cross' 'Medicare' 'Aetna' 'UnitedHealthcare' 'Cigna' 'No tiene']
En la columna: Admission Type, los valores unicos son: ['Urgent' 'Emergency' 'Elective' 'Otro']
En la columna: Medication, los valores unicos son: ['Paracetamol' 'Ibuprofen' 'Aspirin' 'Penicillin' 'Lipitor'
 'No especificado']
En la columna: Test Results, los valores unicos son: ['Normal' 'Inconclusive' 'Abnormal' 'En progreso']

In [79]:
for i in colum_1:
  print (f" -En la columna: {i}, los valores unicos son: {df3[i].value_counts()}")

 -En la columna: Gender, los valores unicos son: Gender
Female    22193
Male      21947
Otro       1935
Name: count, dtype: int64
 -En la columna: Blood Type, los valores unicos son: Blood Type
A+          5560
B+          5550
AB-         5544
B-          5541
A-          5519
AB+         5518
O+          5471
O-          5466
No tiene    1906
Name: count, dtype: int64
 -En la columna: Medical Condition, los valores unicos son: Medical Condition
Arthritis       7790
Hypertension    7743
Diabetes        7724
Cancer          7662
Obesity         7578
Asthma          7578
Name: count, dtype: int64
 -En la columna: Insurance Provider, los valores unicos son: Insurance Provider
Cigna               9009
Medicare            8875
UnitedHealthcare    8770
Blue Cross          8765
Aetna               8741
No tiene            1915
Name: count, dtype: int64
 -En la columna: Admission Type, los valores unicos son: Admission Type
Elective     14971
Urgent       14747
Emergency    14477
Otro          1880
Name: count, dtype: int64
 -En la columna: Medication, los valores unicos son: Medication
Penicillin         8884
Aspirin            8861
Lipitor            8847
Ibuprofen          8802
Paracetamol        8760
No especificado    1921
Name: count, dtype: int64
 -En la columna: Test Results, los valores unicos son: Test Results
Abnormal        14836
Normal          14693
Inconclusive    14667
En progreso      1879
Name: count, dtype: int64

In [80]:
colum_3=['Age', 'Gender', 'Blood Type', 'Medical Condition',
       'Date of Admission','Hospital', 'Insurance Provider',
       'Billing Amount', 'Admission Type', 'Discharge Date',
       'Medication', 'Test Results']

In [81]:
for i in colum_3:
  print (f"En la columna: {i}, los valores unicos son: {df3[i].nunique()}")

En la columna: Age, los valores unicos son: 77
En la columna: Gender, los valores unicos son: 3
En la columna: Blood Type, los valores unicos son: 9
En la columna: Medical Condition, los valores unicos son: 6
En la columna: Date of Admission, los valores unicos son: 1827
En la columna: Hospital, los valores unicos son: 32552
En la columna: Insurance Provider, los valores unicos son: 6
En la columna: Billing Amount, los valores unicos son: 39285
En la columna: Admission Type, los valores unicos son: 4
En la columna: Discharge Date, los valores unicos son: 1854
En la columna: Medication, los valores unicos son: 6
En la columna: Test Results, los valores unicos son: 4

In [82]:
df3

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Hospital,Insurance Provider,Billing Amount,Admission Type,Discharge Date,Medication,Test Results
0,30,Male,B-,Cancer,2024-01-31,Sons and Miller,Blue Cross,18856.281306,Urgent,2024-02-02,Paracetamol,Normal
1,62,Male,A+,Obesity,2019-08-20,Kim Inc,Medicare,33643.327287,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,76,Female,A-,Obesity,2022-09-22,Cook PLC,Aetna,27955.096079,Emergency,2022-10-07,Aspirin,Normal
3,28,Female,O+,Diabetes,2020-11-18,"Hernandez Rogers and Vang,",Medicare,37909.782410,Elective,2020-12-18,Ibuprofen,Abnormal
4,43,Female,AB+,Cancer,2022-09-19,White-White,Aetna,14238.317814,Urgent,2022-10-09,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...
58871,70,Male,A-,Hypertension,2020-01-09,"Little, and Flores Simmons",Medicare,35445.244793,Elective,2020-01-12,Aspirin,Inconclusive
58873,70,Female,AB+,Obesity,2020-09-06,Lowe Group,Aetna,27378.719844,Emergency,2020-09-10,Ibuprofen,Inconclusive
58875,19,Male,No tiene,Cancer,2019-06-07,Williams Inc,Medicare,43520.710165,Elective,2019-06-13,No especificado,Normal
58877,54,Female,A-,Arthritis,2020-09-20,and Kelley Sons,Medicare,1725.826151,Urgent,2020-09-30,No especificado,Abnormal
58881,39,Female,A-,Hypertension,2023-04-21,Ltd Thornton,Cigna,32162.818121,Emergency,2023-04-29,Penicillin,En progreso

In [84]:
df3.to_csv("Base_limpia_proyecto.csv", index=False)